name: Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cpp check install
      run: sudo apt-get install cppcheck 
    - name: cpp check
    - run: cppcheck --enable=all 3_Implementation
    
